//------------------------------------------------------------------------------
// <autogenerated>
//    This code was generated by Measurement Studio.
//    Runtime Version: 9.0.0.292
//
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// <autogenerated>
//------------------------------------------------------------------------------

using NationalInstruments;
using NationalInstruments.DAQmx;
using NationalInstruments.DAQmx.ComponentModel;
using System;
using System.ComponentModel;
using System.Threading;
using System.Collections.Generic;


namespace DaqApplication
{
    /// <summary>
    /// Defines a DAQ component that performs finite input data acquisition
    /// operations.
    /// </summary>
    [System.ComponentModel.DesignerCategory("Code")]
    [ToolboxItem(false)]
    [TemplateData("ReadWfm", MxbFile="DaqTask4474.mxb")]
    partial class DaqTask4474Component : FiniteInputDaqComponent<AnalogMultiChannelReader, AnalogWaveform<double>[]>
    {
        private static readonly object EventReadCompleted = new object();
        private const int DefaultNumberOfSamplesToRead = -1;
        private static readonly TimeSpan DefaultTimeout = TimeSpan.FromMilliseconds(10000);

        public double Rate { get; set; }
        public int SamplePerChannel { get; set; }
        public double Max { get; set; }
        public List<string> DeviceNames { get; set; }
        /// <summary>
        /// Initializes a new instance of the component.
        /// </summary>
        public DaqTask4474Component()
        {
            Initialize();
        }
        
        /// <summary>
        /// Initializes a new instance of the component with the specified container.
        /// </summary>
        public DaqTask4474Component(IContainer container)
            : this()
        {
            if (container != null)
                container.Add(this);
        }
        
        /// <summary>
        /// Creates the underlying DAQ task of the component.
        /// </summary><returns>
        /// A DAQ task that represents the DAQ task of the component.
        /// </returns>
        protected override Task CreateTask()
        {
            DaqTask4474 newTask;
            if (DeviceNames != null)
            {
                newTask = new DaqTask4474(DeviceNames, Rate, SamplePerChannel, Max);
            }
            else
            {
                newTask = new DaqTask4474();
            }
            
            newTask.Stream.Timeout = Convert.ToInt32(DefaultTimeout.TotalMilliseconds);
            return newTask;
        }

        /// <summary>
        /// Creates the underlying DAQ reader of the component.
        /// </summary><returns>
        /// The DAQ reader that performs the input data acquisition operations.
        /// </returns>
        protected override AnalogMultiChannelReader CreateReader()
        {
            return new AnalogMultiChannelReader(Task.Stream);
        }

        /// <summary>
        /// Performs a synchronous read operation with the specified number of
        /// samples to read and returns the acquired data.
        /// </summary><param name="numberOfSamplesToRead">
        /// The number of samples to read in the synchronous read data acquisition.
        /// </param><returns>
        /// A value that contains the result of the synchronous read operation.
        /// </returns>
        public AnalogWaveform<double>[] Read(int numberOfSamplesToRead)
        {
            bool taskAutoStarted = false;

            if (!IsTaskStarted)
            {
                StartTask();
                taskAutoStarted = true;
            }

            AnalogWaveform<double>[] data = ReadFinite(numberOfSamplesToRead);

            if (taskAutoStarted)
                StopTask();

            return data;
        }

        /// <summary>
        /// Performs a synchronous read operation.
        /// </summary><returns>
        /// A value that contains the result of the synchronous read operation.
        /// </returns>
        protected override AnalogWaveform<double>[] ReadFinite()
        {
            return ReadFinite(DefaultNumberOfSamplesToRead);
        }

        private AnalogWaveform<double>[] ReadFinite(int numberOfSamplesToRead)
        {
            return Reader.ReadWaveform(numberOfSamplesToRead);
        }
        
        /// <summary>
        /// Begins an asynchronous read operation.
        /// </summary><param name="callback">
        /// An asynchronous callback that is called when the read is completed.
        /// </param><param name="state">
        /// An object that distinguishes this asynchronous read request from other
        /// requests.
        /// </param>
        protected override void BeginReadFinite(AsyncCallback callback, object state)
        {
            Reader.BeginReadWaveform(DefaultNumberOfSamplesToRead, callback, state);
        }

        /// <summary>
        /// Ends an asynchronous read operation.
        /// </summary><param name="result">
        /// An IAsyncResult that represents an asynchronous call started by
        /// BeginReadFinite.
        /// </param>
        protected override void EndReadFinite(IAsyncResult result)
        {
            try
            {
                AnalogWaveform<double>[] data = Reader.EndReadWaveform(result);

                DaqTask4474ComponentReadCompletedEventArgs args = new DaqTask4474ComponentReadCompletedEventArgs(data);
                RaiseGenericEventAsync(result, OnReadCompleted, args);
            }

            #region Debugger Exception Warnings
            catch (DaqException ex)
            {
                // If you Dispose the component while an asynchronous DAQ operation
                // is still running, the component may already be disposed or may be in the
                // process of disposing when this method is called.  Depending on timing, this situation
                // will result in one of the three errors below.  This is expected behavior.
                //
                // DaqExceptions are processed by the caller of this method in the
                // NationalInstruments.DAQmx.ComponentModel class library.  However, by default,
                // the Visual Studio debugger intercepts these exceptions and breaks
                // the debugger when they occur.
                //
                // Because these exceptions do not represent errors, they are caught and safely discarded
                // here.
                if (ex.Error != -200088 && ex.Error != -88709 && ex.Error != -88710)
                    throw;
            }
            #endregion

        }

        /// <summary>
        /// Raises the ReadCompleted event.
        /// </summary><param name="e">
        /// The event arguments of the ReadCompleted event.
        /// </param>
        protected virtual void OnReadCompleted(DaqTask4474ComponentReadCompletedEventArgs e)
        {
            RaiseGenericEventDirect(EventReadCompleted, e);
        }

        /// <summary>
        /// Occurs when the asynchronous read operation that was initiated by
        /// ReadAsync has completed.
        /// </summary>
        [Category("Action")]
        [Description("Occurs when the asynchronous read operation that was initiated by ReadAsync has completed.")]
        public event EventHandler<DaqTask4474ComponentReadCompletedEventArgs> ReadCompleted
        {
            add
            {
                AddEventHandler(EventReadCompleted, value);
            }

            remove
            {
                RemoveEventHandler(EventReadCompleted, value);
            }
        }
    }

    /// <summary>
    /// Provides data for the ReadCompleted event.
    /// </summary>
    public class DaqTask4474ComponentReadCompletedEventArgs : ReadCompletedEventArgs<AnalogWaveform<double>[]>
    {
        /// <summary>
        /// Initializes a new instance of the ReadCompleted event arguments.
        /// </summary><param name="data">
        /// The data that was acquired from an asynchronous finite input data acquisition.
        /// </param>
        public DaqTask4474ComponentReadCompletedEventArgs(AnalogWaveform<double>[] data)
            : base(data)
        {
        }
    }

    #region Timing Compatibility
    partial class DaqTask4474Component
    {
        /// <summary>
        /// This member supports compatibility with code that is generated with a
        /// different timing mode and is not intended to be used directly from your code.
        /// </summary>
        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Obsolete("This member supports compatibility with code that is generated with a different timing mode and is not intended to be used directly from your code.")]
        public event EventHandler<DaqTask4474ComponentDataReadyEventArgs> DataReady
        {
            add
            {
                throw new NotSupportedException("This member supports compatibility with code that is generated with a different timing mode and is not intended to be used directly from your code.");
            }

            remove
            {
                throw new NotSupportedException("This member supports compatibility with code that is generated with a different timing mode and is not intended to be used directly from your code.");
            }
        }
    }
    
    /// <summary>
    /// This type supports compatibility with code that is generated with a
    /// different timing mode and is not intended to be used directly from your code.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public class DaqTask4474ComponentDataReadyEventArgs : DataReadyEventArgs<object>
    {
        /// <summary>
        /// This member supports compatibility with code that is generated with a
        /// different timing mode and is not intended to be used directly from your code.
        /// </summary>
        public DaqTask4474ComponentDataReadyEventArgs(object data)
            : base(data)
        {
            throw new NotSupportedException("This member supports compatibility with code that is generated with a different timing mode and is not intended to be used directly from your code.");
        }
    }
    #endregion




      
    public class DaqTask4474 : Task
    {
        private double _Rate;
        private int _SamplePerChannel;
        private double _Max;
        private List<string> _DeviceNames;
        public DaqTask4474()
            : this(new List<string>(), 10000, 5000, 10)
        {

        }

        public DaqTask4474(List<string> device, double rate, int samplePerChannel, double max)
        {
            _DeviceNames = device;
            _Rate = rate;
            _SamplePerChannel = samplePerChannel;
            _Max = max;

            Configure();
        }
        
        public virtual void Configure()
        {
            // This code was generated by Measurement Studio.  Changes to this 
            // file may cause incorrect behavior and will be lost if the code 
            // is regenerated.

            foreach (string deviceName in _DeviceNames)
            {
                AIChannel ch = AIChannels.CreateVoltageChannel(deviceName, "", 
                    (AITerminalConfiguration)(-1), 
                    -_Max, _Max, 
                    AIVoltageUnits.Volts);

                ch.Coupling = AICoupling.DC;
            }
            //AIChannels[""].Coupling = AICoupling.AC;
            Timing.ConfigureSampleClock("", _Rate, SampleClockActiveEdge.Rising, SampleQuantityMode.FiniteSamples, _SamplePerChannel);

        }
    }

}
